name: CI

on:
  push: {}
  pull_request: {}
  schedule:
    # run every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jsxstyle
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run jest
        run: yarn run test
      - name: Run karma
        run: yarn run karma-headless-chrome
        env:
          CI: true
          TZ: 'America/Los_Angeles'
